class NetworkSettings:
    NODES_NUMBER_MIN = 2
    ACTION_SLEEP_TIME_SECONDS = 1
    INTERRUPT_ON_ERROR = False
    EXTERNAL_REQUEST_MODE = False
    EXTERNAL_REQUEST_TOTAL_REQUESTS_NUMBER = 1
    NUMBER_OF_REQUESTS = [0, 1, 2]
    WEIGHTS = [0.5, 0.25, 0.25]

settings = NetworkSettings()